import { useEffect, useState } from "react";
import axios from "axios";
import { X, Sparkles, MessageCircle } from "lucide-react";
import { useContext } from "react";
import { AuthContext } from "../../../../context/AuthContext";
import jsPDF from "jspdf";

export default function ClientChatsModal({ patient, initialChat, onClose }) {
  const { user } = useContext(AuthContext);
  const [messages, setMessages] = useState(initialChat || []);
  const [loading, setLoading] = useState(false);
  const [summarizing, setSummarizing] = useState(false);
  const [summary, setSummary] = useState(null);
  const [showSummary, setShowSummary] = useState(false);

  useEffect(() => {
    const fetchPatientChats = async () => {
      if (!patient?.id) return;
      setLoading(true);
      try {
        const res = await axios.get(`http://localhost:3000/chat/${patient.id}`);
        const chats = res.data?.chats || [];
        const normalized = chats.map((c) => ({
          role: c.role === "Client" ? "user" : "bot",
          text: c.message,
          timestamp: c.timestamp,
        }));
        setMessages(normalized);
      } catch (e) {
        // keep initialChat fallback
        // eslint-disable-next-line no-console
        console.error("Failed to load patient chats", e);
      } finally {
        setLoading(false);
      }
    };
    fetchPatientChats();
  }, [patient]);

  // Function to handle chat summarization
  const handleSummarizeChat = async () => {
    if (messages.length === 0) {
      alert("No messages to summarize");
      return;
    }

    setSummarizing(true);
    try {
      const response = await axios.post("http://localhost:3000/chat/summarize", {
        messages: messages
      });
      
      setSummary(response.data);
      setShowSummary(true);
    } catch (error) {
      console.error("Failed to summarize chat:", error);
      alert("Failed to summarize chat. Please try again.");
    } finally {
      setSummarizing(false);
    }
  };

  // Function to download summary as PDF
  const handleDownloadPDF = () => {
    if (!summary) {
      alert("No summary available to download");
      return;
    }

    const doc = new jsPDF();
    
    // Set font and add title
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("Patient Chat Summary", 20, 30);
    
    // Add patient info
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Patient: ${patient?.name || "Unknown"}`, 20, 50);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 60);
    doc.text(`Messages Analyzed: ${summary.messageCount}`, 20, 70);
    
    // Add summary content
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Summary:", 20, 90);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    // Split summary into lines that fit the page width
    const splitSummary = doc.splitTextToSize(summary.summary, 170);
    doc.text(splitSummary, 20, 105);
    
    // Add footer
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by Medora AI", 20, 280);
    
    // Download the PDF
    const fileName = `Chat_Summary_${patient?.name?.replace(/\s+/g, '_') || 'Patient'}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white/95 backdrop-blur-sm rounded-2xl shadow-2xl border border-white/20 w-full max-w-4xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-slate-200/50">
          <div className="flex items-center gap-3">
            <div className="bg-gradient-to-br from-cyan-500 to-sky-500 rounded-xl p-2.5 shadow-md">
              <MessageCircle className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-2xl md:text-3xl font-bold bg-gradient-to-r from-slate-800 to-slate-600 bg-clip-text text-transparent">
                {patient?.name ? `${patient.name}'s Chat` : "Chat History"}
              </h2>
              <p className="text-slate-500 text-sm font-medium">
                {messages.length} message{messages.length !== 1 ? "s" : ""}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2.5 hover:bg-slate-100 rounded-xl text-slate-500 hover:text-slate-700 transition-all duration-200 hover:scale-105"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Chat Content */}
        <div className="flex-1 overflow-hidden">
          {loading ? (
            <div className="h-96 flex flex-col items-center justify-center text-slate-500">
              <div className="bg-gradient-to-br from-slate-100 to-slate-200 rounded-2xl p-8 mb-4">
                <MessageCircle className="w-12 h-12 text-slate-400 mx-auto animate-pulse" />
              </div>
              <p className="text-lg font-medium">Loading chat history...</p>
            </div>
          ) : messages.length === 0 ? (
            <div className="h-96 flex flex-col items-center justify-center">
              <div className="bg-gradient-to-br from-slate-100 to-slate-200 rounded-2xl p-8 mb-6">
                <MessageCircle className="w-16 h-16 text-slate-400 mx-auto" />
              </div>
              <h3 className="text-xl font-bold text-slate-700 mb-2">
                No messages yet
              </h3>
              <p className="text-slate-500 text-center">
                This patient hasn't started any conversations with the chatbot.
              </p>
            </div>
          ) : (
            <div className="p-6 space-y-4 h-96 overflow-y-auto scrollbar-thin scrollbar-thumb-slate-300 scrollbar-track-slate-100 hide-scroll">
              {messages.map((message, index) => (
                <div
                  key={index}
                  className={`flex ${
                    message.role === "user" ? "justify-end" : "justify-start"
                  }`}
                >
                  <div
                    className={`max-w-xs lg:max-w-md xl:max-w-lg px-5 py-4 rounded-2xl shadow-sm ${
                      message.role === "user"
                        ? "bg-gradient-to-r from-cyan-500 to-sky-500 text-white"
                        : "bg-white border border-slate-200 text-slate-800 shadow-md"
                    }`}
                  >
                    <p className="text-sm md:text-base leading-relaxed font-medium">
                      {message.text}
                    </p>
                    {message.timestamp && (
                      <p
                        className={`text-xs mt-2 ${
                          message.role === "user"
                            ? "text-cyan-100"
                            : "text-slate-500"
                        }`}
                      >
                        {new Date(message.timestamp).toLocaleString()}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Summary Button Footer */}
        {messages.length > 0 && !loading && (
          <div className="p-6 border-t border-slate-200/50 bg-slate-50/50 rounded-b-2xl">
            <div className="flex justify-center">
              <button
                type="button"
                disabled={user.subscriptionPlan !== "pro" || summarizing}
                onClick={handleSummarizeChat}
                className={`group flex items-center gap-3 px-6 py-3 ${
                  user.subscriptionPlan !== "pro" || summarizing
                    ? "bg-gray-500/50 cursor-not-allowed"
                    : "bg-gradient-to-r from-cyan-500 to-sky-500"
                } text-white rounded-xl font-semibold shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all duration-300 hover:from-cyan-600 hover:to-sky-600`}
              >
                <Sparkles className={`w-5 h-5 ${summarizing ? "animate-spin" : "group-hover:rotate-12"} transition-transform duration-300`} />
                {summarizing ? "Summarizing..." : "Summarize Chat History"}
                <Sparkles className={`w-5 h-5 ${summarizing ? "animate-spin" : "group-hover:-rotate-12"} transition-transform duration-300`} />
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Summary Modal */}
      {showSummary && summary && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-[60] p-4">
          <div className="bg-white/95 backdrop-blur-sm rounded-2xl shadow-2xl border border-white/20 w-full max-w-3xl max-h-[80vh] flex flex-col">
            {/* Summary Header */}
            <div className="flex justify-between items-center p-6 border-b border-slate-200/50">
              <div className="flex items-center gap-3">
                <div className="bg-gradient-to-br from-emerald-500 to-teal-500 rounded-xl p-2.5 shadow-md">
                  <Sparkles className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h2 className="text-2xl md:text-3xl font-bold bg-gradient-to-r from-slate-800 to-slate-600 bg-clip-text text-transparent">
                    Chat Summary
                  </h2>
                  <p className="text-slate-500 text-sm font-medium">
                    {summary.messageCount} messages analyzed
                  </p>
                </div>
              </div>
              <button
                onClick={() => setShowSummary(false)}
                className="p-2.5 hover:bg-slate-100 rounded-xl text-slate-500 hover:text-slate-700 transition-all duration-200 hover:scale-105"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            {/* Summary Content */}
            <div className="flex-1 overflow-hidden p-6">
              <div className="h-96 overflow-y-auto scrollbar-thin scrollbar-thumb-slate-300 scrollbar-track-slate-100">
                <div className="bg-gradient-to-br from-slate-50 to-slate-100 rounded-xl p-6 border border-slate-200">
                  <div className="prose prose-slate max-w-none">
                    <pre className="whitespace-pre-wrap text-slate-700 text-sm leading-relaxed font-medium">
                      {summary.summary}
                    </pre>
                  </div>
                </div>
              </div>
            </div>

            {/* Summary Footer */}
            <div className="p-6 border-t border-slate-200/50 bg-slate-50/50 rounded-b-2xl">
              <div className="flex justify-between items-center">
                <div className="text-sm text-slate-600">
                  <p>Generated by Medora AI • {new Date().toLocaleDateString()}</p>
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={() => setShowSummary(false)}
                    className="px-4 py-2 text-slate-600 hover:text-slate-800 border border-slate-300 hover:border-slate-400 rounded-lg font-medium transition-all duration-200"
                  >
                    Close
                  </button>
                  <button
                    onClick={() => {
                      // Simple copy to clipboard
                      navigator.clipboard.writeText(summary.summary);
                      alert("Summary copied to clipboard!");
                    }}
                    className="px-4 py-2 bg-gradient-to-r from-cyan-500 to-sky-500 text-white rounded-lg font-medium hover:from-cyan-600 hover:to-sky-600 transition-all duration-200 shadow-lg hover:shadow-xl"
                  >
                    Copy Summary
                  </button>
                  <button
                    onClick={handleDownloadPDF}
                    className="px-4 py-2 bg-gradient-to-r from-emerald-500 to-teal-500 text-white rounded-lg font-medium hover:from-emerald-600 hover:to-teal-600 transition-all duration-200 shadow-lg hover:shadow-xl"
                  >
                    Download PDF
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
